title: Jordan Benrezkallah # your name (or website title) here
logo: "/images/photo_profil_compressed_500kb.png?raw=true" # your photo (or logo) here
description: > 
  Data Scientist pursuing a Ph.D. focused on spatio-temporal data on pollinators at a European scale. Actively engaged in the <a href="https://www.wildposh.eu/">WildPosh</a> project, which focuses on pesticide impacts, while also exploring artificial intelligence applications for biodiversity monitoring.


  <a href="https://www.linkedin.com/in/jordan-benrezkallah/">View My LinkedIn Profile</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
# google_analytics: UA-000000-0 # Uncomment and set your Google Analytics tracking ID here if needed
